### PR TITLE
Update German and Croatian translations

### PR DESCRIPTION
**Pull request by milotype**

### CODE REVIEW

**Comment by billiob** [comment]
Danke schön!
My german is very rusty. I shouldn't try to do more than that!

**Comment by milotype** [comment]
BTW, your link `http://terminolo.gy/` is broken, it returns a 403 page

**Comment by billiob** [comment]
Thanks, should be fixed now.

**Comment by milotype** [comment]
Yes it is fixed!
Can you please add informations about supported languages somewhere on the website? 
Maybe as an menu item "Languages"!
And maybe add "Contributing Translation" info on the "Contribute" page

**Comment by billiob** [comment]
It's not as easy because the website is not only about terminology.
I've looked at using an online tool to get Terminology translated but couldn't find something that would work. I've yet to test transifex though.

About the Contribute page, it's actually a wiki that you can edit. Be aware that the usual way is to send translations through the dedicated mailing list.
Myself, I do appreciate pull-request here as much.

**Comment by milotype** [comment]
You could check these online tools in the order of my preference as translator ;-)
Weblate
Crowding
Transifex
Launchpad

**Comment by billiob** [comment]
I've asked 10 days ago to have an opensource account for Terminology on Weblate but got no answer ☹

**Comment by billiob** [comment]
Terminology is now on Weblate!
Thanks for the suggestion.

**Comment by milotype** [comment]
Great! Weblate is a good choice!

As mentioned before, is there any chance to add some information on the website about translations/localizations – at least on the page `https://www.enlightenment.org/about-terminology`?

Something like:
"_Terminology has been translated into several languages already. If your language is missing or incomplete, please use Weblate to help translate Terminology._"

Also, maybe you could use one of the widgets from `https://hosted.weblate.org/widgets/terminology/
`

**Comment by billiob** [comment]
Thanks for the suggestion. I've done the changes.

**Pull request merged**
