### PR TITLE
Doing some work on tyls

### PR DESCRIPTION
**Pull request by Emeraude**
I started to improve tyls command :
I refactoring size_print function (it now supports zotta and yotta, and make it safer)
It now supports the **-a** option, that show also hidden files. (So issue #6 is done now)
Arguments can be passed in the order you want.
I remove a lot of memory leak (before there were 50% of memory lost, now it's only 0.5%)

### CODE REVIEW

**Comment by Emeraude** [comment]
I fix all of this.

**Comment by billiob** [comment]
Sorry to be picky.
When doing changes, you should actually rewrites the patches and push them to the branch.
Your commit messages aren't that great. They should be one short message, a blank line and then a larger description of the changes and why they were made.
You should have 3 patches: one about the "size_print" function, one about adding the "-a" option and one to fix the write() bug (and also fix the leak: it's not really a leak here, it's good to do it correctly though).

**Comment by Emeraude** [comment]
Thanks for your tips.
So, I changed my commits to make their messages better.
I hope it's better now.

**Comment by billiob** [comment]
I've committed your patches. You should run `git config user.name Thibaut Broggi`.
There was an unused variable. You can compile terminology with more warnings wit the following: `CFLAGS="-g -ggdb3 -Werror -Wall -Wextra -Wshadow -O0 -pipe" ./autogen.sh`.
There was an arithmetic exception in `size_print`. I rewrote it to make it simpler and hopefully bug-free.

If you still want to work on tyls, you could make it use ecore_getopt and then take some inspiration from http://bsago.me/exa/ (but not the git part just yet).
Or you can pick a task on https://phab.enlightenment.org/maniphest/query/iyex1KK8ZZ9M/#R (you need to be logged in).

**Pull request closed without merging**
